version: 5.0.0.{build}
clone_folder: c:\projects\nlogweb
configuration: Release
image: Visual Studio 2019
platform: Any CPU

nuget:
  project_feed: true
matrix:
  fast_finish: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: quiet
  
skip_tags: true

build_script:
  - ps: .\build.ps1

deploy:
- provider: NuGet
  api_key:
    secure: N/3SLEg4r4QlbIVrI6epIHgv2KfwkwkrIUeLRyqS8D3AkC29Ql86NMkHxWOfcmUM
  on:
    branch: master
test_script:
  - dotnet test NLog.Web.sln

artifacts:
- path: '**\NLog.Web.*.nupkg'
- path: '**\NLog.Web.*.snupkg'
